#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://localhost:3306/flightsdatabase
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring:
  application:
    name: flight-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    showSql: true
  datasource:
    url: jdbc:mysql://localhost:3306/flightsdatabase
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 0
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
